export 'package:flutter/material.dart';

export '../../config/vistas.dart';
export '../../views/adelanto/adelantoscreen.dart';
// export '../../views/adelanto/pedir_adelanto.dart';
export '../../views/adelanto/valores_pedir_adelanto.dart';
export '../../views/docshtml/html_view.dart';
//export '../../views/auth_screen.dart';
export '../../views/firma/firma.dart';
export '../../views/home/homescreen.dart';
// export '../../views/adelanto/valores_pedir_adelanto.dart';
export '../../views/inicio/splashscreen.dart';
export '../../views/login/login.dart';
//export '../../views/display.dart';
export '../../views/misadelantos/mis_adelantos.dart';
export '../../views/otrapantalla/otra_pantalla.dart';
export '../../views/pdfs/pdf_view.dart';
//export '../../views/splash_Screen.dart';
export '../../views/servicios/serviciosscreen.dart';
export '../../views/solicitudes/solicitudes.dart';
//export '../../views/splash_Screen.dart';
export '../views/adelanto/actualizaempleado.dart';
export '../views/firma/signaturepage.dart';
export '../views/misservicios/servicios_activos.dart';
// export '../views/prestamos/prestamo_nomina.dart';
export '../views/recibos/recibosnomina.dart';
export '../views/recibosnomina/recibosnomina.dart';
export '../views/xmls/xml.dart';
